--RECEITA.VO

--INCLUIR RECEITA
CREATE OR REPLACE PROCEDURE INCLUIRRECEITA(NOME VARCHAR2, ID_CATEGORIA NUMBER, ID_USUARIO NUMBER, PORCAO NUMBER, TEMPO_PREPARO NUMBER, MODO_PREPARO VARCHAR2, IMG_PATH VARCHAR2, PONTUACAO_MEDIA NUMBER, VIEWS NUMBER, FAVS NUMBER, SLUG VARCHAR2, APROVADO NUMBER)
IS
BEGIN
    INSERT INTO RECEITAS(ID, NOME, ID_CATEGORIA, ID_USUARIO, PORCAO, TEMPO_PREPARO, MODO_PREPARO, IMG_PATH, PONTUACAO_MEDIA, VIEWS, FAVS, SLUG, APROVADO) VALUES(RECEITA_SEQ.NEXTVAL, NOME, ID_CATEGORIA, ID_USUARIO, PORCAO, TEMPO_PREPARO, MODO_PREPARO, IMG_PATH, PONTUACAO_MEDIA, VIEWS, FAVS, SLUG, APROVADO);
END;
/

--EXEC INCLUIRRECEITA(VO.GETNOME(), VO.GETCATEGORIAID(), VO.GETUSUARIOID(), VO.GETPORCAO(), VO.GETTEMPOPREPARO(), VO.GETMODOPREPARO(), VO.GETIMGPATH(), VO.GETPONTUACAOMEDIA(), VO.GETVIEWS(), VO.GETFAVS(), VO.GETSLUG(),0);
    
--SELECIONAR ULTIMO ID INSERIDO

CREATE OR REPLACE VIEW ULTIMOINSERIDO
AS
    SELECT MAX(ID) ID FROM RECEITAS;

--SELECT * FROM ULTIMOINSERIDO;

--LISTAR TODAS AS RECEITAS APROVADAS

CREATE OR REPLACE VIEW LISTARTODASRECEITASAPROVADAS
AS
    SELECT ID, NOME, IMG_PATH, PONTUACAO_MEDIA, FAVS, (SELECT COUNT(ID) FROM COMENTARIOS GROUP BY ID_RECEITA HAVING ID_RECEITA = R.ID) COMENTARIOS FROM RECEITAS R WHERE APROVADO = 1;

--SELECT * FROM LISTARTODASRECEITASAPROVADAS;

--LISTAR TODAS AS RECEITAS ADMIN

CREATE OR REPLACE VIEW LISTARTODASADMIN
AS
    SELECT * FROM RECEITAS;

--SELECT * FROM LISTARTODASADMIN;

--LISTAR RECEITAS POR ID DA RECEITA

CREATE OR REPLACE PROCEDURE LISTARPORID(IDRECEITA NUMBER)
IS
BEGIN
    SELECT * FROM RECEITAS WHERE ID = IDRECEITA;
END;
/

--EXEC LISTARPORID(RECEITAID);

CREATE OR REPLACE PROCEDURE ATUALIZARRECEITA(NOME VARCHAR2, ID_CATEGORIA NUMBER, ID_USUARIO NUMBER, PORCAO NUMBER, TEMPO_PREPARO NUMBER, MODO_PREPARO VARCHAR2, IMG_PATH VARCHAR2, PONTUACAO_MEDIA NUMBER, VIEWS NUMBER, FAVS NUMBER, SLUG VARCHAR2, APROVADO NUMBER, ID NUMBER)
IS
BEGIN
    UPDATE RECEITAS SET NOME = NOME, ID_CATEGORIA = ID_CATEGORIA, ID_USUARIO = ID_USUARIO, PORCAO = PORCAO, TEMPO_PREPARO = TEMPO_PREPARO, MODO_PREPARO = MODO_PREPARO, IMG_PATH = IMG_PATH, PONTUACAO_MEDIA = PONTUACAO_MEDIA, VIEWS = VIEWS, FAVS = FAVS, SLUG = SLUG, APROVADO = APROVADO WHERE ID = ID;
END;
/
            
--EXEC ATUALIZARRECEITA(VO.GETNOME(), VO.GETCATEGORIAID(), VO.GETUSUARIOID(), VO.GETPORCAO(), VO.GETTEMPOPREPARO(), VO.GETMODOPREPARO(), VO.GETIMGPATH(), VO.GETPONTUACAOMEDIA(), VO.GETVIEWS(), VO.GETFAVS(), VO.GETSLUG(), VO.GETAPROVADO(), VO.GETID())

--REMOVER RECEITA POR ID

CREATE OR REPLACE PROCEDURE REMOVERRECEITA(ID NUMBER)
IS
BEGIN
    DELETE FROM RECEITAS WHERE ID = ID;
END;/

--EXEC REMOVERRECEITA(RECEITA.GETID());

--UTENSILIOS LINKADOS A RECEITA

CREATE OR REPLACE PROCEDURE LISTARUTENSILIOSDARECEITA(IDRECEITA NUMBER)
IS
BEGIN
    SELECT U.ID, U.NOME FROM UTENSILIOS U INNER JOIN RECEITAS_UTENSILIOS RU ON RU.ID_RECEITA = IDRECEITA AND RU.ID_UTENSILIO = U.ID;
END;
/

--EXEC LISTARUTENSILIOSDARECEITA(RECEITA.GETID())

--SELECIONAR POR NOME

CREATE OR REPLACE PROCEDURE SELECIONARPORNOME(TERMOPESQUISA VARCHAR2)
IS
BEGIN
    SELECT ID, NOME, IMG_PATH, PONTUACAO_MEDIA, FAVS, (SELECT COUNT(ID) FROM COMENTARIOS GROUP BY ID_RECEITA HAVING ID_RECEITA = A.ID) COMENTARIOS FROM RECEITAS A WHERE LOWER(NOME) LIKE LOWER(TERMOPESQUISA) AND APROVADO = 1;
END;
/

--EXEC SELECIONARPORNOME(TERMOPESQUISA);
